### ISSUE TITLE
fix open handles

### ISSUE THREAD

**Issue by iolo** [day1co/http-request-sync#6]
It looks like `https.request` makes open handles.

```
Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      19 |
      20 |     const request = isHttps ? https.request : http.request;
    > 21 |     const req = request(options, (res: IncomingMessage) => {
         |                 ^
      22 |       log('statusCode:', res.statusCode);
      23 |       log('headers:', res.headers);
      24 |       res.setEncoding('utf8');

      at http-request-async.ts:21:17
      at httpRequestAsync (http-request-async.ts:13:10)
      at Object.<anonymous> (http-request-async.spec.ts:19:41)
      at TestScheduler.scheduleTests (../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (../node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (../node_modules/@jest/core/build/cli/index.js:173:3)


  ●  TLSWRAP

      19 |
      20 |     const request = isHttps ? https.request : http.request;
    > 21 |     const req = request(options, (res: IncomingMessage) => {
         |                 ^
      22 |       log('statusCode:', res.statusCode);
      23 |       log('headers:', res.headers);
      24 |       res.setEncoding('utf8');

      at http-request-async.ts:21:17
      at httpRequestAsync (http-request-async.ts:13:10)
      at Object.<anonymous> (http-request-async.spec.ts:25:41)
      at TestScheduler.scheduleTests (../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (../node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (../node_modules/@jest/core/build/cli/index.js:173:3)
```

**Comment by moonimooni** [comment]
https://github.com/facebook/jest/issues/11665#issuecomment-961947393
이 문제인것 같습니다
